[project]
name = "todoapprd"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rahul Dave <rahuldave@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
server = "python app.py"

[dependencies]
flask = ">=3.0.3,<3.1"
flask-sqlalchemy = ">=3.0.3,<3.1"
