[project]
name = "todoapprd"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
populate = "python -m todoapp.sql"                                 # runs stuff in name==__main__
server = "gunicorn -w 4 -b0.0.0.0:5000 'todoapp.app:create_app()'"
devserver = "python -m todoapp.app"                                # runs stuff in name==__main__

[dependencies]
flask = ">=3.0.3,<3.1"
gunicorn = ">=22.0.0,<22.1"
python-dotenv = ">=1.0.1,<1.1"
pydantic = ">=2.7.4,<2.8"

[pypi-dependencies]
todoapprd = { path = ".", editable = true }

[feature.test.dependencies]
pytest = ">=7.2.0,<7.3"
pytest-cov = ">=2.5.1,<2.6"
pytest-mock = ">=3.14.0,<3.15"

[feature.test.tasks]
test = "pytest --cov -m 'not e2e'"
test_e2e = "pytest --cov -m 'e2e'"

[feature.lintformat.dependencies]
ruff = ">=0.4.10,<0.5"
pre-commit = ">=3.1.1,<3.2"

[feature.lintformat.tasks]
lint = "ruff check"
format = "ruff format"

[feature.typing.dependencies]
mypy = ">=1.10.0,<1.11"

[feature.typing.tasks]
typing = "mypy ."

[feature.docs.dependencies]
quarto = ">=1.4.550,<1.5"
nbdev = ">=2.2.10,<2.3"

[feature.build.dependencies]
build = ">=0.7.0,<0.8"
twine = ">=3.3.0,<3.4"

[environments]
default = { solve-group = "default" } # includes ['default']
build = { features = ["build"], solve-group = "default" } # ['default, 'build']
dev = { features = [
    "test",
    "lintformat",
    "typing",
    "docs",
], solve-group = "default" } # ['default', 'test', 'lintformat']
