[project]
name = "todoapprd"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
populate = "python -m todoapp.sql"                  # runs stuff in name==__main__
server = "gunicorn -w 4 -b0.0.0.0:5000 todoapp:app"
devserver = "python -m todoapp.app"                 # runs stuff in name==__main__

[dependencies]
flask = ">=3.0.3,<3.1"
gunicorn = ">=22.0.0,<22.1"
python-dotenv = ">=1.0.1,<1.1"

[pypi-dependencies]
todoapprd = { path = ".", editable = true }
